### ISSUE TITLE
Code coverage fails when running cypress in headless mode

### ISSUE THREAD

**Issue by praneetha-ck-robo** [cypress-io/code-coverage#148]
Running `npm run cypress:open`  runs all test cases correctly and  generates the code coverage report also. 

But when I am running the tests in headless mode, i.e when I run `npm run cypress:run` , I get the following error.

```
 CypressError: cy.task('coverageReport') failed with the following error:

> TypeError: Command failed: nyc report --report-dir ./coverage --temp-dir /Volumes/Development/Projects/merchant-ops-panel/frontend/.nyc_output --reporter=lcov --reporter=clover --reporter=json
timedPromise.finally is not a function
    at setExitHandler (/Volumes/Development/Projects/merchant-ops-panel/frontend/node_modules/@cypress/code-coverage/node_modules/execa/lib/kill.js:102:29)
    at execa (/Volumes/Development/Projects/merchant-ops-panel/frontend/node_modules/@cypress/code-coverage/node_modules/execa/index.js:100:22)
    at coverageReport (/Volumes/Development/Projects/merchant-ops-panel/frontend/node_modules/@cypress/code-coverage/task.js:116:12)
    at invoke (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:41:14)
    at /Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:48:16
    at tryCatcher (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.wrapChildPromise (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:47:28)
    at Object.wrap (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/task.js:48:8)
    at execute (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:94:12)
    at EventEmitter.ipc.on (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:153:5)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at process.<anonymous> (/Users/pck/Library/Caches/Cypress/3.4.1/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


Because this error occurred during a 'after all' hook we are skipping all of the remaining tests.
      at Object.cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85348:11)
      at Object.throwErr (http://localhost:3000/__cypress/runner/cypress_runner.js:85303:18)
      at Object.throwErrByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:85335:17)
      at http://localhost:3000/__cypress/runner/cypress_runner.js:75372:23
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:118962:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:116898:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:116955:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:117000:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:117075:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:3000/__cypress/runner/cypress_runner.js:113687:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113697:10)
      at Async.drainQueues (http://localhost:3000/__cypress/runner/cypress_runner.js:113571:14)
      at <anonymous>


```

My package.json file

```
  "devDependencies": {
        "@cypress/code-coverage": "^1.12.2",
        "cypress": "3.4.1",
        "cypress-file-upload": "3.4.0",
        "start-server-and-test": "1.10.0",
        "@cypress/instrument-cra": "1.0.0",
        "istanbul-lib-coverage": "3.0.0",
        "nyc": "14.1.1"
    }
"scripts": {
        "start": "react-scripts start",
        "cy:open": "cypress open",
        "cypress:open": "start-server-and-test start-inst http-get://localhost:3000 cy:open",
        "cy:run": "cypress run --spec 'cypress/integration/**/*.spec.js'",
        "cypress:run": "start-server-and-test start-inst http-get://localhost:3000 cy:run",
        "report:coverage": "nyc report --reporter=html",
        "report:coverage:text": "nyc report --reporter=text",
    }
```
Node version - **v12.16.1**
NPM version - **6.13.4**
OS- macOS - **High Sierra Version 10.13.6**

I have used this as a reference as mentioned in the cypress official docs, since I am using create-react-app. https://github.com/bahmutov/testing-react

**Comment by bahmutov** [comment]
Try using a newer version of Cypress

**Comment by praneetha-ck-robo** [comment]
@bahmutov - Upgrading to the latest version worked, thank you!
