### ISSUE TITLE
 Error running plugin: Error: Cannot find module 'coffeescript'

### ISSUE THREAD

**Issue by Jaguirre123** [cypress-io/code-coverage#30]
I'm trying to add the cypress code-coverage module to my app but I'm getting this error. 
<img width="830" alt="Screen Shot 2019-07-09 at 11 52 07 AM" src="https://user-images.githubusercontent.com/35276012/60915324-71102180-a240-11e9-8243-5f1a9da65864.png">

**Comment by bahmutov** [comment]
@Jaguirre123 

can you copy paste the stack trace from the error? Right now the image cuts off the right side of each line so I cannot see where the problem originates

**Comment by bahmutov** [comment]
also, has the `npm install` or `npm ci` step finished successfully?

**Comment by Jaguirre123** [comment]
@bahmutov 
<img width="772" alt="Screen Shot 2019-07-08 at 7 37 46 PM" src="https://user-images.githubusercontent.com/35276012/60919886-b84fdf80-a24b-11e9-8872-cea577200fbd.png">

**Comment by Jaguirre123** [comment]
@bahmutov 
<img width="1508" alt="Screen Shot 2019-07-09 at 1 15 47 PM" src="https://user-images.githubusercontent.com/35276012/60919923-ca318280-a24b-11e9-9d85-1bf127d3e1ce.png">

**Comment by Jaguirre123** [comment]
Yes the install steps finished successfully

**Comment by Jaguirre123** [comment]
This issue is fixed now. Does this plugin works for older versions of babel? 
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/jesseaguirre/Desktop/webapp/node_modules/babel-preset-react/lib/index.js while parsing file: /Users/jesseaguirre/Desktop/webapp/tests/cypress/e2e/sonic/message/delete-message.cy.js

**Comment by bahmutov** [comment]
Older versions of Babel - I have not tested it

**Comment by bahmutov** [comment]
"This issue is fixed now" - if this resolves the problem @Jaguirre123 could you close the issue?

**Comment by dthisner** [comment]
I am seeing this issue today
`**Title:** Error running plugin

**Message:** The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.

**Details:** Error: Cannot find module 'coffeescript'
Require stack:
- /Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/coffeeify/index.js
- /Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/module-deps/index.js
- /Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/browserify/index.js
- /Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/@cypress/browserify-preprocessor/index.js
- /Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/cypress-cucumber-preprocessor/lib/index.js
- /Users/dennis/Projects/src/applydigital.co/simplelease-webapp/cypress/plugins/index.js
- /Users/dennis/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js
- /Users/dennis/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/coffeeify/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at nr (/Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/module-deps/index.js:302:21)
    at onfile (/Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/resolve/lib/async.js:106:21)
    at onex (/Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/resolve/lib/async.js:161:32)
    at /Users/dennis/Projects/src/applydigital.co/simplelease-webapp/node_modules/resolve/lib/async.js:11:20
    at callback (/Users/dennis/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:166:5)

**Stack trace:**
```
Error: The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.
    at Object.get (/Users/dennis/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/errors.js:344:11)
    at EventEmitter.handleError (/Users/dennis/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:113:24)
    at EventEmitter.emit (events.js:203:13)
    at ChildProcess.<anonymous> (/Users/dennis/Library/Caches/Cypress/4.0.2/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:25:29)
    at ChildProcess.emit (events.js:203:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

````

**Comment by dthisner** [comment]
Seem to be able to have fixed it, some of my files had traces of TestCafe in them and I fixed those up and the error went away :)

**Comment by dthisner** [comment]
Wow, that is really weird! 
I was using TestCafe before with gherkin 
```    
"gherkin-testcafe": "2.5.0",
    "testcafe": "1.8.1"
```
The moment I remove TestCafe and I run `npm install` and then run `Cypress`, I am getting the CoffeeScript crash.

**Comment by bahmutov** [comment]
Seems to me the solutions is to remove traces of other dependencies, remove `node_modules` and run install again.
