### ISSUE TITLE
Support custom `nyc.config.js` file in ESM projects

### ISSUE THREAD

**Issue by mike-plummer** [cypress-io/code-coverage#668]
Based off @cypress-io/cypress#26729

ESM projects cannot currently use a custom `nyc.config.js` file because this project uses `require(..)` to import that file - `require` does not support ESM modules.

![Screenshot 2023-06-21 at 3 21 52 PM](https://github.com/cypress-io/code-coverage/assets/11482842/2d0004fa-fe88-4202-aa2b-fed853c697ce)

**Logs and screenshots**

```
Error: Failed to load nyc.config.js: require() of ES Module /Users/mikep/Development/Scaffolds/firewatch/26729/nyc.config.js from /Users/mikep/Development/Scaffolds/firewatch/26729/node_modules/@cypress/code-coverage/task-utils.js not supported.
Instead change the require of nyc.config.js in /Users/mikep/Development/Scaffolds/firewatch/26729/node_modules/@cypress/code-coverage/task-utils.js to a dynamic import() which is available in all CommonJS modules.
    at readNycOptions (/Users/mikep/Development/Scaffolds/firewatch/26729/node_modules/@cypress/code-coverage/task-utils.js:61:13)
    at getNycOption (/Users/mikep/Development/Scaffolds/firewatch/26729/node_modules/@cypress/code-coverage/task.js:36:28)
    at Object. (/Users/mikep/Development/Scaffolds/firewatch/26729/node_modules/@cypress/code-coverage/task.js:58:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap. (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async loadFile (/Users/mikep/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:106:14)
    at async EventEmitter. (/Users/mikep/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:116:32)
```

**Link to the repo**

**Comment by Benoit-Vasseur** [comment]
Hello,

+1 for ESM support

You may use this package to load the config ? https://github.com/istanbuljs/load-nyc-config

**Comment by dword-design-honestly** [comment]
I'm using `nyc.config.cjs`, but it's obviously not optimal.

**Comment by robin-ln** [comment]
maybe just use https://github.com/istanbuljs/load-nyc-config ?
